# Using on proxy environment
services:
  demo-app:
    image: tomcat:9.0.95-jre17
    restart: unless-stopped
    volumes:
      - ./api/build/libs/Random-Food.war:/usr/local/tomcat/webapps/ROOT.war
      - ./data:/usr/local/tomcat/webapps/uploads

networks:
  default:
    external: true
    name: proxy-cloud
